# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_hotel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(unique=True),
        ),
    ]
